---
new_page_extension: md
auto_deploy: false
admin_path: foadm
webhook_url: 
sections:
- type: heading
  label: Content
upload_dir: src/_static/img
public_path: "/_static/img"
front_matter_path: ".forestry/front_matter/templates"
use_front_matter_path: true
file_template: ":filename:"
build:
  preview_output_directory: _site
  install_dependencies_command: npm install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run start
