---
name: Web11
author: CG
baseurl: "https://web11.pages.dev/"
locale: vi # default locale.
dir: "ltr" # default locale direction.
locales:   # available locales.
  - label: "English"
    code: en
    active: True
  - label: "Tieng viet"
    code: vi
    active: True
